name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          MYSQL_ROOT_PASSWORD: 2424
          MYSQL_DATABASE: gestion_gimnasio

    steps:
      - uses: actions/checkout@v4

      - name: List files in workspace
        run: ls -al

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysqladmin ping -h 127.0.0.1 -P 3306 --silent; do
            echo "MySQL is unavailable - sleeping"
            sleep 10
          done

      - name: List Docker containers
        run: docker ps -a

      - name: Check MySQL Container Logs
        run: docker logs $(docker ps -q -f ancestor=mysql:8.0)

      - name: Run Gradle Build and Tests
        run: ./gradlew build

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run Gradle Dependency Check
        run: ./gradlew dependencyUpdates

  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          MYSQL_ROOT_PASSWORD: 2424
          MYSQL_DATABASE: gestion_gimnasio

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysqladmin ping -h 127.0.0.1 -P 3306 --silent; do
            echo "MySQL is unavailable - sleeping"
            sleep 10
          done

      - name: Run Gradle Tests
        run: ./gradlew test

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test
